# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cloudapp_api}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Aaron Russell"]
  s.date = %q{2010-10-18}
  s.description = %q{A simple Ruby wrapper for the CloudApp API. Uses HTTParty with a simple ActiveResource-like interface.}
  s.email = %q{aaron@gc4.co.uk}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "cloudapp_api.gemspec",
     "lib/cloudapp/base.rb",
     "lib/cloudapp/client.rb",
     "lib/cloudapp/httparty.rb",
     "lib/cloudapp/monkey_patch/httparty.rb",
     "lib/cloudapp/monkey_patch/net_digest_auth.rb",
     "lib/cloudapp/multipart.rb",
     "lib/cloudapp_api.rb",
     "test/helper.rb",
     "test/helper/methods.rb",
     "test/setup_faking.rb",
     "test/test_cloudapp_api.rb",
     "test/test_config.sample.yml"
  ]
  s.homepage = %q{http://github.com/aaronrussell/cloud_app}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A simple Ruby wrapper for the CloudApp API. Uses HTTParty with a simple ActiveResource-like interface.}
  s.test_files = [
    "test/helper/methods.rb",
     "test/helper.rb",
     "test/setup_faking.rb",
     "test/test_cloudapp_api.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0.5.2"])
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<httparty>, [">= 0.5.2"])
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0.5.2"])
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

